author: mpy-dev-ml
author_url: https://github.com/mpy-dev-ml
github_url: https://github.com/mpy-dev-ml/UmbraCore
module: UmbraCore
output: docs
theme: apple
swift_build_tool: spm
build_tool_arguments:
  - -Xswiftc
  - -swift-version
  - -Xswiftc
  - "6.0.3"
documentation: "*.md"
abstract: "*.md"
custom_categories:
  - name: Getting Started
    children:
      - Installation
      - QuickStart
  - name: Core Services
    children:
      - UmbraKeychainService
      - UmbraCryptoService
      - UmbraBookmarkService
  - name: Security
    children:
      - SecurityTypes
      - CryptoTypes
  - name: Utilities
    children:
      - UmbraLogging
      - UmbraXPC
clean: true
skip_undocumented: false
hide_documentation_coverage: false
min_acl: public
