# Site settings
title: UmbraCore Documentation
description: Documentation for the UmbraCore secure backup programme
url: "https://mpy-dev-ml.github.io"
baseurl: "/UmbraCore"
source: "."

# Theme settings
remote_theme: mpy-dev-ml/umbra-docs-theme@v0.1.0
theme_color: blue

markdown: kramdown
highlighter: rouge

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate

# Search settings
search:
  enabled: true
  label: Search

# Collections
collections:
  docs:
    permalink: /:collection/:path/
    output: true
  guides:
    permalink: /:collection/:path/
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: docs
      nav_order: 1
  - scope:
      path: "guides"
    values:
      nav_order: 2
  - scope:
      path: "api"
    values:
      nav_order: 3
  - scope:
      path: "security"
    values:
      nav_order: 4

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
