remote_theme: just-the-docs/just-the-docs

# Site settings
title: UmbraCore Documentation
description: Documentation for the UmbraCore backup management library
baseurl: "/UmbraCore"
url: "https://mpy-dev-ml.github.io"

# Theme settings
search_enabled: true
heading_anchors: true
color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "UmbraCore on GitHub":
    - "https://github.com/mpy-dev-ml/UmbraCore"

# Footer content
footer_content: "Copyright &copy; 2025 mpy-dev-ml. Distributed under the MIT license."

# Collections for organizing documentation
collections:
  guides:
    output: true
    permalink: /:collection/:path/
  api:
    output: true
    permalink: /:collection/:path/

# Default YAML front matter
defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: default
      nav_order: 2
  - scope:
      path: ""
      type: api
    values:
      layout: default
      nav_order: 3
  - scope:
      path: "security"
    values:
      nav_order: 4
