# Site settings
title: UmbraCore Documentation
description: Documentation for the UmbraCore Swift Package
url: ""
baseurl: "/UmbraCore"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - setup_theme.sh

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:path/
  api:
    output: true
    permalink: /:collection/:path/
  contributing:
    output: true
    permalink: /:collection/:path/
  security:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
