# Site settings
title: UmbraCore Documentation
description: Documentation for the UmbraCore secure backup programme
url: "https://mpy-dev-ml.github.io"
baseurl: "/UmbraCore"

# Build settings
theme: doks-theme
markdown: kramdown
highlighter: rouge

# Theme settings
doks:
  color_theme: blue
  header:
    logo:
      text: UmbraCore
      image: false
    nav:
      - name: Docs
        url: /docs/
      - name: API
        url: /api/
      - name: GitHub
        url: https://github.com/mpy-dev-ml/UmbraCore

# SASS settings
sass:
    sass_dir: ../../themeforest/doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ../../themeforest/doks-theme/_layouts
includes_dir: ../../themeforest/doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'Gemfile', 'Gemfile.lock', 'node_modules', 'vendor', '.git', '.github' ]
permalink: /:title/

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Search settings
search_enabled: true
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "UmbraCore on GitHub":
    - "https://github.com/mpy-dev-ml/UmbraCore"

# Collections for organizing documentation
collections:
  guides:
    output: true
    permalink: /:collection/:path/
  api:
    output: true
    permalink: /:collection/:path/

# Default YAML front matter
defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: default
      nav_order: 2
  - scope:
      path: ""
      type: api
    values:
      layout: default
      nav_order: 3
  - scope:
      path: "security"
    values:
      nav_order: 4
