# Site settings
title: UmbraCore Documentation
description: Documentation for the UmbraCore backup management library
url: "https://mpy-dev-ml.github.io"
baseurl: "/UmbraCore"

# Build settings
remote_theme: h-enk/doks
markdown: kramdown

# Theme settings
doks:
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: UmbraCore
            image: # Add logo later if needed
        nav:
            - item_name: Getting Started
              item_url: '/getting-started'
            - item_name: Guides
              item_url: '/guides'
            - item_name: API
              item_url: '/api'
            - item_name: Security
              item_url: '/security'
            - item_name: Contributing
              item_url: '/contributing'
    footer:
        content:
            logo:
                text: UmbraCore
                image: # Add logo later if needed
            copyright: Copyright &copy; 2025 mpy-dev-ml. Distributed under the MIT license.
        social_list:
            - network_name: github
              profile_url: 'https://github.com/mpy-dev-ml/UmbraCore'

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Search settings
search_enabled: true
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "UmbraCore on GitHub":
    - "https://github.com/mpy-dev-ml/UmbraCore"

# Collections for organizing documentation
collections:
  guides:
    output: true
    permalink: /:collection/:path/
  api:
    output: true
    permalink: /:collection/:path/

# Default YAML front matter
defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: default
      nav_order: 2
  - scope:
      path: ""
      type: api
    values:
      layout: default
      nav_order: 3
  - scope:
      path: "security"
    values:
      nav_order: 4
