# Site settings
title: UmbraCore Documentation
description: Documentation for the UmbraCore secure backup programme
url: "https://mpy-dev-ml.github.io"
baseurl: "/UmbraCore"

# Theme settings
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.7.0

# Color scheme
color_scheme: light

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Search settings
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Aux links for the upper right navigation
aux_links:
  "UmbraCore on GitHub":
    - "//github.com/mpy-dev-ml/UmbraCore"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Collections
collections:
  docs:
    permalink: /:collection/:path/
    output: true
  guides:
    permalink: /:collection/:path/
    output: true

# Default layouts
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default
      nav_order: 1
  - scope:
      path: "guides"
    values:
      nav_order: 2
  - scope:
      path: "api"
    values:
      nav_order: 3
  - scope:
      path: "security"
    values:
      nav_order: 4

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
