name: CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: self-hosted
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
      ARCHS: arm64
      ONLY_ACTIVE_ARCH: YES
      ROSETTA_DISABLED: 1
      MACOSX_DEPLOYMENT_TARGET: 14.0

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: System Info
      run: |
        system_profiler SPSoftwareDataType
        xcodebuild -version
        swift --version
        bazel --version

    - name: Clean Bazel Cache
      run: |
        rm -rf /tmp/bazel-cache
        rm -rf /tmp/bazel-repo-cache
        rm -rf ~/.cache/bazel
        rm -rf ~/.cache/bazelisk
        bazel clean --expunge
        mkdir -p /tmp/bazel-cache
        mkdir -p /tmp/bazel-repo-cache

    - name: Build
      run: |
        # Ensure we're running on arm64
        arch -arm64 bazel build //... \
          --spawn_strategy=local \
          --genrule_strategy=local \
          --strategy=Genrule=local \
          --strategy=SwiftCompile=local \
          --platforms=//:macos_arm64

    - name: Core Tests
      run: |
        arch -arm64 bazel test //Tests/UmbraCoreTests/... \
          --spawn_strategy=local \
          --test_strategy=standalone \
          --platforms=//:macos_arm64 \
          --test_output=errors

    - name: Security Tests
      run: |
        arch -arm64 bazel test //Tests/SecurityTypesTests/... //Tests/CryptoTypesTests/... \
          --spawn_strategy=local \
          --test_strategy=standalone \
          --platforms=//:macos_arm64 \
          --test_output=errors

    - name: Generate Coverage
      run: |
        arch -arm64 bazel coverage //... \
          --spawn_strategy=local \
          --strategy=CoverageReport=local \
          --platforms=//:macos_arm64 \
          --combined_report=lcov

    - name: Upload Coverage
      uses: codecov/codecov-action@v4
      with:
        files: bazel-out/_coverage/_coverage_report.dat
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Cleanup
      if: always()
      run: |
        rm -rf /tmp/bazel-cache/*
        rm -rf /tmp/bazel-repo-cache/*
