name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk

permissions:
  contents: read
  security-events: write
  id-token: read

jobs:
  build-and-test:
    name: Build & Test
    runs-on: [self-hosted, macOS, ARM64]
    
    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
        fetch-depth: 0

    - name: System Info
      run: |
        uname -a
        swift --version
        bazel --version

    - name: Configure Bazel
      run: |
        cat >> .bazelrc << 'EOF'
        build --cpu=darwin_arm64
        build --apple_platform_type=macos
        build --macos_minimum_os=14.0
        build --features=swift.use_global_module_cache
        build --features=swift.enable_batch_mode
        build --features=swift.enable_concurrency_checking
        build --verbose_failures
        test --test_output=errors
        EOF

    - name: Setup Test Environment
      run: |
        mkdir -p ~/UmbraTest/{Core,Security,Coverage}
        chmod -R 755 ~/UmbraTest

    - name: Build
      run: |
        bazel build //... --show_progress_rate_limit=5

    - name: Core Tests
      env:
        UMBRA_TEST_ROOT: ~/UmbraTest/Core
      run: |
        bazel test //... \
          --test_tag_filters=-security,-requires_keychain \
          --test_env=UMBRA_TEST_ROOT

    - name: Security Tests
      env:
        UMBRA_TEST_ROOT: ~/UmbraTest/Security
      run: |
        bazel test //... \
          --test_tag_filters=security \
          --test_env=UMBRA_TEST_ROOT

    - name: Generate Coverage
      env:
        UMBRA_TEST_ROOT: ~/UmbraTest/Coverage
      run: |
        # Generate coverage data
        bazel coverage //... \
          --collect_code_coverage \
          --instrument_test_targets \
          --experimental_generate_llvm_lcov \
          --coverage_report_generator=@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main \
          --combined_report=lcov \
          --test_env=UMBRA_TEST_ROOT \
          --verbose_failures \
          --test_output=errors
        
        # Create coverage directory
        mkdir -p coverage
        
        # Find coverage file in bazel-out/_coverage
        COVERAGE_FILE="$(pwd)/bazel-out/_coverage/_coverage_report.dat"
        if [ -f "$COVERAGE_FILE" ]; then
          echo "Found coverage file at: $COVERAGE_FILE"
          cp "$COVERAGE_FILE" coverage/lcov.info
          echo "Coverage file contents:"
          head -n 5 coverage/lcov.info
        else
          echo "Error: Coverage file not found at $COVERAGE_FILE"
          echo "Searching for any coverage files:"
          find bazel-out -type f -name "*coverage*.dat" -ls
          exit 1
        fi

    - name: Upload Coverage
      uses: codecov/codecov-action@v4
      with:
        files: coverage/lcov.info
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: mpy-dev-ml/UmbraCore

    - name: Cleanup
      if: always()
      run: |
        rm -rf ~/UmbraTest
        bazel clean --expunge
