name: CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: self-hosted
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: System Info
      run: |
        system_profiler SPSoftwareDataType
        xcodebuild -version
        swift --version
        bazel --version

    - name: Configure Bazel
      run: |
        echo "build --config=macos" >> .bazelrc.local
        echo "test --config=macos" >> .bazelrc.local

    - name: Clean Bazel Cache
      run: |
        rm -rf /tmp/bazel-cache
        rm -rf /tmp/bazel-repo-cache
        rm -rf ~/.cache/bazel
        rm -rf ~/.cache/bazelisk
        bazel clean --expunge
        mkdir -p /tmp/bazel-cache
        mkdir -p /tmp/bazel-repo-cache

    - name: Build
      run: bazel build //... --config=macos --show_progress_rate_limit=5

    - name: Core Tests
      run: bazel test //Tests/UmbraCoreTests/... --config=macos --test_output=errors

    - name: Security Tests
      run: bazel test //Tests/SecurityTypesTests/... //Tests/CryptoTypesTests/... --config=macos --test_output=errors

    - name: Generate Coverage
      run: |
        bazel coverage //... --config=macos --combined_report=lcov

    - name: Upload Coverage
      uses: codecov/codecov-action@v4
      with:
        files: bazel-out/_coverage/_coverage_report.dat
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Cleanup
      if: always()
      run: |
        rm -rf /tmp/bazel-cache/*
        rm -rf /tmp/bazel-repo-cache/*
