name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  BAZEL_VERSION: 6.4.0
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk

jobs:
  build-and-test:
    name: Build and Test
    runs-on: [self-hosted, macOS, ARM64]
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Bazel
      uses: bazelbuild/setup-bazelisk@v2

    - name: Configure Build Environment
      run: |
        echo "DEVELOPER_DIR=$DEVELOPER_DIR" >> $GITHUB_ENV
        echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV
        sudo xcode-select -s $DEVELOPER_DIR
        xcrun --sdk macosx --show-sdk-path

    - name: Configure Bazel
      run: |
        cat > .bazelrc.local << EOF
        build --verbose_failures
        build --cpu=darwin_arm64
        build --apple_platform_type=macos
        build --macos_minimum_os=13.0
        build --host_macos_minimum_os=13.0
        test --test_output=errors
        EOF

    - name: Mount Bazel Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazelisk
        key: ${{ runner.os }}-arm64-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE') }}
        restore-keys: |
          ${{ runner.os }}-arm64-bazel-

    - name: Build
      run: |
        bazel build //... \
          --cpu=darwin_arm64 \
          --apple_platform_type=macos

    - name: Run Tests
      run: |
        bazel test //... \
          --cpu=darwin_arm64 \
          --apple_platform_type=macos \
          --test_output=errors

    - name: Generate Coverage Report
      run: |
        bazel coverage //... \
          --cpu=darwin_arm64 \
          --apple_platform_type=macos \
          --combined_report=lcov \
          --instrumentation_filter="^//Sources" \
          --coverage_report_generator=@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: bazel-out/_coverage/_coverage_report.dat
        fail_ci_if_error: true
        verbose: true

  release:
    name: Create Release
    needs: build-and-test
    runs-on: [self-hosted, macOS, ARM64]
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Bazel
      uses: bazelbuild/setup-bazelisk@v2

    - name: Configure Build Environment
      run: |
        echo "DEVELOPER_DIR=$DEVELOPER_DIR" >> $GITHUB_ENV
        echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV
        sudo xcode-select -s $DEVELOPER_DIR

    - name: Build Release Artifacts
      run: |
        bazel build //... \
          --cpu=darwin_arm64 \
          --apple_platform_type=macos \
          --compilation_mode=opt

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bazel-bin/**/*
        draft: false
        prerelease: false
        generate_release_notes: true
