name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - 'requirements.txt'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: [self-hosted, macos]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Debug - Check Files
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing directory contents:"
          ls -la
          echo "Looking for mkdocs.yml:"
          find . -name "mkdocs.yml" -type f

      # Use a simpler Python installation approach
      - name: Install Dependencies
        run: |
          python3 -m pip install --user mkdocs mkdocs-material

      - name: Build Documentation
        run: |
          python3 -m mkdocs build --verbose
          # Ensure the CNAME file is copied to the site directory
          if [ -f docs/CNAME ]; then
            cp docs/CNAME site/
            echo "Copied CNAME file to the site directory"
          else
            echo "Warning: CNAME file not found in docs directory"
          fi

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd site
          git init
          git add .
          git commit -m "Deploy documentation update"
          git branch -M gh-pages
          git remote add origin https://\${{ github.actor }}:\${{ secrets.GITHUB_TOKEN }}@github.com/\${{ github.repository }}.git
          git push -f origin gh-pages
