name: Deploy Documentation

on:
  push:
    branches:
      - main
      - feature/mkdocs-migration  # Include this branch during development
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-bootstrap386 pymdown-extensions

      - name: Build and deploy documentation
        run: |
          mkdocs gh-deploy --force
