name: Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-documentation:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "6.0.3"
    
    - name: Install jazzy
      run: |
        gem install jazzy
        
    - name: Generate Documentation
      run: |
        jazzy \
          --author "mpy-dev-ml" \
          --author_url https://github.com/mpy-dev-ml \
          --github_url https://github.com/mpy-dev-ml/UmbraCore \
          --github-file-prefix https://github.com/mpy-dev-ml/UmbraCore/blob/main \
          --module-version main \
          --module UmbraCore \
          --theme apple \
          --swift-build-tool spm \
          --build-tool-arguments -Xswiftc,-swift-version,-Xswiftc,6.0.3
          
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        full_commit_message: "docs: update documentation for ${{ github.sha }}"
