name: UmbraCore Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run with additional debug logging'
        required: false
        default: false
        type: boolean

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
  SWIFT_DETERMINISTIC_HASHING: 1

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Run Stable Tests
    runs-on: [self-hosted, macOS, ARM64]
    
    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
        fetch-depth: 0
      
    - name: Setup Xcode
      run: |
        xcode-select --print-path
        swift --version

    - name: Install Bazelisk
      run: |
        brew install bazelisk || true
        bazelisk --version
        
    - name: Prepare Test Targets
      id: prepare-tests
      run: |
        # Create a file listing all stable test targets
        cat > stable_test_targets.txt << EOL
        //Tests/CoreTests:CoreTests
        //Tests/CryptoTests:CryptoTests
        //Tests/KeychainTests:KeychainTests
        //Tests/ModelsTests:ModelsTests
        //Tests/ResourcesTests:ResourcesTests
        //Tests/ResticTypesTests:ResticTypesTests
        //Tests/SecurityImplementationTests:SecurityImplementationTests
        //Tests/UmbraTestKit/Tests:UmbraTestKitTests
        //Tests/UmbraXPCTests:UmbraXPCTests
        EOL
        
        # Count targets
        TARGET_COUNT=$(wc -l < stable_test_targets.txt | xargs)
        echo "Found $TARGET_COUNT stable test targets"
        
        # Enable additional debugging if requested
        if [[ "${{ github.event.inputs.debug_enabled }}" == "true" ]]; then
          echo "Debug mode enabled - extra test output will be shown"
          echo "Test targets to be run:"
          cat stable_test_targets.txt
        fi
          
    - name: Run Stable Tests
      run: |
        echo "Running stable tests with ci_tests configuration..."
        TEST_OUTPUT_FLAG="--test_output=errors"
        
        if [[ "${{ github.event.inputs.debug_enabled }}" == "true" ]]; then
          TEST_OUTPUT_FLAG="--test_output=all"
        fi
        
        bazelisk test --config=ci_tests $TEST_OUTPUT_FLAG --flaky_test_attempts=3 --keep_going $(cat stable_test_targets.txt)
          
    - name: Summarise Test Results
      if: always()
      run: |
        TARGET_COUNT=$(wc -l < stable_test_targets.txt | xargs)
        echo "Completed testing of $TARGET_COUNT stable test targets"
        echo "ResticCLIHelperTests were excluded as they require special environment setup"
        
        # List any tests with build issues that weren't attempted
        echo "The following tests currently have build issues and were not included:"
        echo "- BookmarkTests"
        echo "- LoggingTests"
        echo "- UmbraSecurityTests"
        echo "- XPCTests"
