name: Core Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run with additional debug logging'
        required: false
        default: false
        type: boolean

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  SWIFT_DETERMINISTIC_HASHING: 1
  BAZEL_TEST_TIMEOUT: "600"  # 10 minute timeout for individual tests

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Run Stable Tests
    runs-on: [self-hosted, macOS, ARM64]
    timeout-minutes: 60  # Set a job-level timeout
    
    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
        fetch-depth: 0
      
    - name: Setup Xcode
      run: |
        xcode-select --print-path
        swift --version

    - name: Install Bazelisk
      run: |
        brew install bazelisk || true
        bazelisk --version
        
    - name: Prepare Test Targets
      id: prepare-tests
      run: |
        # Create a file listing all stable test targets
        cat > stable_test_targets.txt << EOL
        //Tests/CoreTests:CoreTests
        //Tests/CryptoTests:CryptoTests
        //Tests/CryptoTypesTests:CryptoTypesTests
        //Tests/ErrorHandlingProtocolsTests:ErrorHandlingProtocolsTests
        //Tests/KeychainTests:KeychainTests
        //Tests/ModelsTests:ModelsTests
        //Tests/ResourcesTests:ResourcesTests
        //Tests/ResticTypesTests:ResticTypesTests
        //Tests/SecurityImplementationTests:SecurityImplementationTests
        //Tests/UmbraTestKit/Tests:UmbraTestKitTests
        //Tests/UmbraXPCTests:UmbraXPCTests
        //Sources/CoreErrors/Tests:CoreErrorsTests
        EOL
        
        # Count targets
        TARGET_COUNT=$(wc -l < stable_test_targets.txt | xargs)
        echo "Found $TARGET_COUNT stable test targets"
        
        # Enable additional debugging if requested
        if [[ "${{ github.event.inputs.debug_enabled }}" == "true" ]]; then
          echo "Debug mode enabled - extra test output will be shown"
          echo "Test targets to be run:"
          cat stable_test_targets.txt
        fi
          
    - name: Run Stable Tests
      timeout-minutes: 45  # Set a step-level timeout
      run: |
        echo "Running stable tests with ci_tests configuration..."
        TEST_OUTPUT_FLAG="--test_output=errors"
        
        if [[ "${{ github.event.inputs.debug_enabled }}" == "true" ]]; then
          TEST_OUTPUT_FLAG="--test_output=all"
        fi
        
        # Run tests with standard settings (matching production)
        bazelisk test \
          --config=ci_tests \
          $TEST_OUTPUT_FLAG \
          --flaky_test_attempts=1 \
          --test_verbose_timeout_warnings \
          --show_progress_rate_limit=5 \
          --keep_going \
          $(cat stable_test_targets.txt)
          
    - name: Generate Coverage Report
      if: success()
      run: |
        echo "Generating code coverage report..."
        # Generate coverage report for all source files
        bazelisk coverage \
          --combined_report=lcov \
          --instrumentation_filter="^//Sources" \
          --test_output=errors \
          --nocache_test_results \
          $(cat stable_test_targets.txt)
        
        # The coverage report will be in bazel-out/_coverage/_coverage_report.dat
        # Convert LCOV to a format that Codecov can understand
        mkdir -p coverage_reports
        cp bazel-out/_coverage/_coverage_report.dat coverage_reports/lcov.info
        
        echo "Code coverage report generated successfully"
        
    - name: Upload Coverage to Codecov
      if: success()
      uses: codecov/codecov-action@v4
      with:
        files: coverage_reports/lcov.info
        name: UmbraCore-Coverage
        fail_ci_if_error: false
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Handle Swift Warnings
      if: always()
      run: |
        echo "Note: There are several Swift concurrency warnings in the codebase."
        echo "These are mainly related to Sendable conformance and will be errors in Swift 6."
        echo "These warnings do not affect the functionality of the current tests."

    - name: Summarise Test Results
      if: always()
      run: |
        TARGET_COUNT=$(wc -l < stable_test_targets.txt | xargs)
        echo "Completed testing of $TARGET_COUNT stable test targets"
        
        # List any tests with build issues that weren't attempted
        echo "The following tests currently have build issues and were not included:"
        echo "- BookmarkTests"
        echo "- LoggingTests" 
        echo "- ResticCLIHelperTests"
        echo "- UmbraSecurityTests" 
        echo "- XPCTests"
