name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  test:
    runs-on: [self-hosted, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Prepare Test Environment
        run: |
          brew install bazelisk || true
          bazelisk --version
          brew install yq || true
          yq --version
          
      - name: Discover Test Targets
        run: |
          echo "Discovering test targets..."
          chmod +x team-utils/discover_test_targets.sh
          ./team-utils/discover_test_targets.sh
          
      - name: Run Tests
        run: |
          echo "Running all tests..."
          bazelisk test --define=build_environment=nonlocal -k --verbose_failures $(cat team-utils/test_targets.txt)
          
      - name: Summarise Test Results
        run: |
          TEST_COUNT=$(wc -l < team-utils/test_targets.txt | xargs)
          echo "Completed $TEST_COUNT test targets"
          
        if: always()
