name: Run Tests

on:
  push:

  pull_request:


jobs:
  test:
    runs-on: [self-hosted, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Prepare Test Environment
        run: |
          brew install bazelisk || true
          bazelisk --version
          
      - name: Run Tests
        run: |
          echo "Running all tests..."
          bazelisk test --define=build_environment=nonlocal -k --verbose_failures $(cat team-utils/test_targets.txt)
          
      - name: Summarise Test Results
        run: |
          TEST_COUNT=$(wc -l < team-utils/test_targets.txt | xargs)
          echo "Completed $TEST_COUNT test targets"
          
        if: always()
