name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  core-tests:
    name: Core Tests
    runs-on: [self-hosted, macOS, ARM64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: System Info
      run: |
        uname -a
        swift --version
        bazel --version
        
    - name: Resolve Dependencies
      run: |
        swift package resolve
      
    - name: Build
      run: |
        bazel build //... --show_progress_rate_limit=5
      
    - name: Run Core Tests
      run: |
        bazel test //... \
          --test_tag_filters=-security,-requires_keychain \
          --test_output=errors \
          --verbose_failures

  security-tests:
    name: Security Tests
    needs: core-tests
    runs-on: [self-hosted, macOS, ARM64]
    environment: security-testing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Resolve Dependencies
      run: |
        swift package resolve
        
    - name: Setup Test Environment
      run: |
        mkdir -p ~/UmbraTest/Security
        chmod 755 ~/UmbraTest/Security
        
    - name: Run Security Tests
      env:
        UMBRA_TEST_ROOT: ~/UmbraTest/Security
      run: |
        bazel test //... \
          --test_tag_filters=security \
          --test_env=UMBRA_TEST_ROOT \
          --test_output=errors \
          --verbose_failures
        
    - name: Cleanup
      if: always()
      run: |
        rm -rf ~/UmbraTest/Security

  coverage:
    needs: [core-tests, security-tests]
    runs-on: [self-hosted, macOS, ARM64]
    steps:
    - uses: actions/checkout@v4
    
    - name: Resolve Dependencies
      run: |
        swift package resolve
          
    - name: Generate Coverage
      env:
        UMBRA_TEST_ROOT: ~/UmbraTest/Coverage
      run: |
        mkdir -p ~/UmbraTest/Coverage
        bazel coverage //... \
          --test_output=errors \
          --experimental_generate_llvm_lcov \
          --combined_report=lcov \
          --test_env=UMBRA_TEST_ROOT
        
    - name: Process Coverage Report
      run: |
        find -L "$(bazel info output_path)/_coverage/_coverage_report.dat" \
          -name "coverage.dat" -exec cp {} coverage.dat \;
        
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        files: coverage.dat
        fail_ci_if_error: false
        verbose: true
        
    - name: Cleanup
      if: always()
      run: |
        rm -rf ~/UmbraTest/Coverage
