name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: [self-hosted, macOS, ARM64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: System Info
      run: |
        uname -a
        swift --version
        bazel --version
        
    - name: Resolve Dependencies
      run: |
        swift package resolve
      
    - name: Build
      run: |
        bazel build //... --show_progress_rate_limit=5
      
    - name: Run Tests
      run: |
        bazel test //... --test_output=errors

  coverage:
    needs: build-and-test
    runs-on: [self-hosted, macOS, ARM64]
    steps:
    - uses: actions/checkout@v4
    
    - name: Resolve Dependencies
      run: |
        swift package resolve
          
    - name: Generate Coverage
      run: |
        bazel coverage //... \
          --test_output=errors \
          --experimental_generate_llvm_lcov \
          --combined_report=lcov
        
    - name: Process Coverage Report
      run: |
        find -L "$(bazel info output_path)/_coverage/_coverage_report.dat" \
          -name "coverage.dat" -exec cp {} coverage.dat \;
        
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        files: coverage.dat
        fail_ci_if_error: false
        verbose: true
